// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomPromptEntry(arg1) {
  return window['go']['backend']['App']['AddCustomPromptEntry'](arg1);
}

export function AddCustomRoot(arg1, arg2, arg3) {
  return window['go']['backend']['App']['AddCustomRoot'](arg1, arg2, arg3);
}

export function AddFavorite(arg1) {
  return window['go']['backend']['App']['AddFavorite'](arg1);
}

export function AddImageToFavoriteGroup(arg1, arg2) {
  return window['go']['backend']['App']['AddImageToFavoriteGroup'](arg1, arg2);
}

export function AddLauncherTool(arg1) {
  return window['go']['backend']['App']['AddLauncherTool'](arg1);
}

export function AddPromptTemplate(arg1) {
  return window['go']['backend']['App']['AddPromptTemplate'](arg1);
}

export function AddPromptToolLink(arg1) {
  return window['go']['backend']['App']['AddPromptToolLink'](arg1);
}

export function AddTagToImage(arg1, arg2) {
  return window['go']['backend']['App']['AddTagToImage'](arg1, arg2);
}

export function BatchAddTag(arg1, arg2) {
  return window['go']['backend']['App']['BatchAddTag'](arg1, arg2);
}

export function BatchDeleteTags(arg1) {
  return window['go']['backend']['App']['BatchDeleteTags'](arg1);
}

export function BatchDeleteTrash(arg1) {
  return window['go']['backend']['App']['BatchDeleteTrash'](arg1);
}

export function BatchFavorites(arg1, arg2) {
  return window['go']['backend']['App']['BatchFavorites'](arg1, arg2);
}

export function BatchMove(arg1, arg2) {
  return window['go']['backend']['App']['BatchMove'](arg1, arg2);
}

export function BatchRemoveTag(arg1, arg2) {
  return window['go']['backend']['App']['BatchRemoveTag'](arg1, arg2);
}

export function BatchRestoreTrash(arg1) {
  return window['go']['backend']['App']['BatchRestoreTrash'](arg1);
}

export function CleanEmptyFolders() {
  return window['go']['backend']['App']['CleanEmptyFolders']();
}

export function CleanupFavoriteReferences() {
  return window['go']['backend']['App']['CleanupFavoriteReferences']();
}

export function CleanupTags() {
  return window['go']['backend']['App']['CleanupTags']();
}

export function ClearPreviewCache() {
  return window['go']['backend']['App']['ClearPreviewCache']();
}

export function ClearUserProfileImage() {
  return window['go']['backend']['App']['ClearUserProfileImage']();
}

export function CopyText(arg1) {
  return window['go']['backend']['App']['CopyText'](arg1);
}

export function CreateAutoRule(arg1) {
  return window['go']['backend']['App']['CreateAutoRule'](arg1);
}

export function CreateFavoriteGroup(arg1) {
  return window['go']['backend']['App']['CreateFavoriteGroup'](arg1);
}

export function CreateTag(arg1, arg2, arg3) {
  return window['go']['backend']['App']['CreateTag'](arg1, arg2, arg3);
}

export function DeleteAutoRule(arg1) {
  return window['go']['backend']['App']['DeleteAutoRule'](arg1);
}

export function DeleteCustomPromptEntry(arg1) {
  return window['go']['backend']['App']['DeleteCustomPromptEntry'](arg1);
}

export function DeleteCustomRoot(arg1) {
  return window['go']['backend']['App']['DeleteCustomRoot'](arg1);
}

export function DeleteFavoriteGroup(arg1) {
  return window['go']['backend']['App']['DeleteFavoriteGroup'](arg1);
}

export function DeleteImage(arg1) {
  return window['go']['backend']['App']['DeleteImage'](arg1);
}

export function DeleteImageNote(arg1) {
  return window['go']['backend']['App']['DeleteImageNote'](arg1);
}

export function DeleteLauncherTool(arg1) {
  return window['go']['backend']['App']['DeleteLauncherTool'](arg1);
}

export function DeletePromptTemplate(arg1) {
  return window['go']['backend']['App']['DeletePromptTemplate'](arg1);
}

export function DeletePromptToolLink(arg1) {
  return window['go']['backend']['App']['DeletePromptToolLink'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['backend']['App']['DeleteTag'](arg1);
}

export function EmptyTrash() {
  return window['go']['backend']['App']['EmptyTrash']();
}

export function ExportImages(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ExportImages'](arg1, arg2, arg3);
}

export function ExtractIcon(arg1) {
  return window['go']['backend']['App']['ExtractIcon'](arg1);
}

export function GetAutoRules() {
  return window['go']['backend']['App']['GetAutoRules']();
}

export function GetCustomPromptEntries() {
  return window['go']['backend']['App']['GetCustomPromptEntries']();
}

export function GetCustomRoots() {
  return window['go']['backend']['App']['GetCustomRoots']();
}

export function GetDirectoryBinding() {
  return window['go']['backend']['App']['GetDirectoryBinding']();
}

export function GetDirectoryHealthSummary() {
  return window['go']['backend']['App']['GetDirectoryHealthSummary']();
}

export function GetFavoriteGroups() {
  return window['go']['backend']['App']['GetFavoriteGroups']();
}

export function GetFavorites() {
  return window['go']['backend']['App']['GetFavorites']();
}

export function GetGalleryPerformanceSettings() {
  return window['go']['backend']['App']['GetGalleryPerformanceSettings']();
}

export function GetImageGallerySummary() {
  return window['go']['backend']['App']['GetImageGallerySummary']();
}

export function GetImageMetadata(arg1) {
  return window['go']['backend']['App']['GetImageMetadata'](arg1);
}

export function GetImageNotes() {
  return window['go']['backend']['App']['GetImageNotes']();
}

export function GetImageTags() {
  return window['go']['backend']['App']['GetImageTags']();
}

export function GetImages(arg1, arg2) {
  return window['go']['backend']['App']['GetImages'](arg1, arg2);
}

export function GetImagesIndex(arg1, arg2) {
  return window['go']['backend']['App']['GetImagesIndex'](arg1, arg2);
}

export function GetImagesPage(arg1) {
  return window['go']['backend']['App']['GetImagesPage'](arg1);
}

export function GetLauncherTools() {
  return window['go']['backend']['App']['GetLauncherTools']();
}

export function GetPromptAssistantState() {
  return window['go']['backend']['App']['GetPromptAssistantState']();
}

export function GetPromptLibraryEntries() {
  return window['go']['backend']['App']['GetPromptLibraryEntries']();
}

export function GetPromptTemplates() {
  return window['go']['backend']['App']['GetPromptTemplates']();
}

export function GetPromptToolLinks() {
  return window['go']['backend']['App']['GetPromptToolLinks']();
}

export function GetRelativePath(arg1) {
  return window['go']['backend']['App']['GetRelativePath'](arg1);
}

export function GetShortcutActions() {
  return window['go']['backend']['App']['GetShortcutActions']();
}

export function GetShortcutSettings() {
  return window['go']['backend']['App']['GetShortcutSettings']();
}

export function GetStatistics(arg1) {
  return window['go']['backend']['App']['GetStatistics'](arg1);
}

export function GetSubFolders(arg1) {
  return window['go']['backend']['App']['GetSubFolders'](arg1);
}

export function GetTags() {
  return window['go']['backend']['App']['GetTags']();
}

export function GetTrashList() {
  return window['go']['backend']['App']['GetTrashList']();
}

export function GetTrashSettings() {
  return window['go']['backend']['App']['GetTrashSettings']();
}

export function GetUserProfile() {
  return window['go']['backend']['App']['GetUserProfile']();
}

export function GetUtilityMenuSettings() {
  return window['go']['backend']['App']['GetUtilityMenuSettings']();
}

export function GetWindowBehaviorSettings() {
  return window['go']['backend']['App']['GetWindowBehaviorSettings']();
}

export function GetWorkbenchAggregate(arg1) {
  return window['go']['backend']['App']['GetWorkbenchAggregate'](arg1);
}

export function MoveCustomRoot(arg1, arg2) {
  return window['go']['backend']['App']['MoveCustomRoot'](arg1, arg2);
}

export function OpenCurrentOutputDirectory() {
  return window['go']['backend']['App']['OpenCurrentOutputDirectory']();
}

export function OpenCurrentRootDirectory() {
  return window['go']['backend']['App']['OpenCurrentRootDirectory']();
}

export function OpenFile(arg1) {
  return window['go']['backend']['App']['OpenFile'](arg1);
}

export function OpenImageLocation(arg1) {
  return window['go']['backend']['App']['OpenImageLocation'](arg1);
}

export function OrganizeFiles(arg1) {
  return window['go']['backend']['App']['OrganizeFiles'](arg1);
}

export function PinCustomRoot(arg1) {
  return window['go']['backend']['App']['PinCustomRoot'](arg1);
}

export function RemoveFavorite(arg1) {
  return window['go']['backend']['App']['RemoveFavorite'](arg1);
}

export function RemoveImageFromFavoriteGroup(arg1, arg2) {
  return window['go']['backend']['App']['RemoveImageFromFavoriteGroup'](arg1, arg2);
}

export function RemoveTagFromImage(arg1, arg2) {
  return window['go']['backend']['App']['RemoveTagFromImage'](arg1, arg2);
}

export function RestoreMainWindow() {
  return window['go']['backend']['App']['RestoreMainWindow']();
}

export function RestoreTrash(arg1) {
  return window['go']['backend']['App']['RestoreTrash'](arg1);
}

export function RunAutoRulesNow() {
  return window['go']['backend']['App']['RunAutoRulesNow']();
}

export function RunDirectoryHealthAction(arg1) {
  return window['go']['backend']['App']['RunDirectoryHealthAction'](arg1);
}

export function RunLauncherTool(arg1) {
  return window['go']['backend']['App']['RunLauncherTool'](arg1);
}

export function SaveDirectoryBinding(arg1, arg2) {
  return window['go']['backend']['App']['SaveDirectoryBinding'](arg1, arg2);
}

export function SaveGalleryPerformanceSettings(arg1) {
  return window['go']['backend']['App']['SaveGalleryPerformanceSettings'](arg1);
}

export function SaveOutputDirectory(arg1) {
  return window['go']['backend']['App']['SaveOutputDirectory'](arg1);
}

export function SavePromptAssistantState(arg1) {
  return window['go']['backend']['App']['SavePromptAssistantState'](arg1);
}

export function SaveShortcutSettings(arg1) {
  return window['go']['backend']['App']['SaveShortcutSettings'](arg1);
}

export function SaveTrashSettings(arg1) {
  return window['go']['backend']['App']['SaveTrashSettings'](arg1);
}

export function SaveUserProfile(arg1) {
  return window['go']['backend']['App']['SaveUserProfile'](arg1);
}

export function SaveUtilityMenuSettings(arg1) {
  return window['go']['backend']['App']['SaveUtilityMenuSettings'](arg1);
}

export function SelectFolder() {
  return window['go']['backend']['App']['SelectFolder']();
}

export function SelectUserProfileImage() {
  return window['go']['backend']['App']['SelectUserProfileImage']();
}

export function ServeImage(arg1, arg2) {
  return window['go']['backend']['App']['ServeImage'](arg1, arg2);
}

export function SetAutoRulesEnabled(arg1) {
  return window['go']['backend']['App']['SetAutoRulesEnabled'](arg1);
}

export function SetImageFavoriteGroups(arg1, arg2) {
  return window['go']['backend']['App']['SetImageFavoriteGroups'](arg1, arg2);
}

export function SetImageNote(arg1, arg2) {
  return window['go']['backend']['App']['SetImageNote'](arg1, arg2);
}

export function ShowCompactWindow() {
  return window['go']['backend']['App']['ShowCompactWindow']();
}

export function ToggleAlwaysOnTop(arg1) {
  return window['go']['backend']['App']['ToggleAlwaysOnTop'](arg1);
}

export function UpdateAutoRule(arg1) {
  return window['go']['backend']['App']['UpdateAutoRule'](arg1);
}

export function UpdateCustomRoot(arg1, arg2, arg3) {
  return window['go']['backend']['App']['UpdateCustomRoot'](arg1, arg2, arg3);
}

export function UpdateCustomRootEnabled(arg1, arg2) {
  return window['go']['backend']['App']['UpdateCustomRootEnabled'](arg1, arg2);
}

export function UpdateFavoriteGroup(arg1, arg2) {
  return window['go']['backend']['App']['UpdateFavoriteGroup'](arg1, arg2);
}

export function UpdateLauncherTool(arg1, arg2) {
  return window['go']['backend']['App']['UpdateLauncherTool'](arg1, arg2);
}

export function UpdatePromptTemplate(arg1, arg2) {
  return window['go']['backend']['App']['UpdatePromptTemplate'](arg1, arg2);
}

export function UpdatePromptToolLink(arg1, arg2) {
  return window['go']['backend']['App']['UpdatePromptToolLink'](arg1, arg2);
}

export function UpdateTag(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['UpdateTag'](arg1, arg2, arg3, arg4);
}

export function UploadImages(arg1, arg2) {
  return window['go']['backend']['App']['UploadImages'](arg1, arg2);
}
