// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {http} from '../models';

export function AddCustomPromptEntry(arg1:backend.PromptLibraryEntry):Promise<backend.PromptLibraryEntry>;

export function AddCustomRoot(arg1:string,arg2:string,arg3:string):Promise<backend.CustomRoot>;

export function AddFavorite(arg1:string):Promise<void>;

export function AddImageToFavoriteGroup(arg1:string,arg2:string):Promise<void>;

export function AddLauncherTool(arg1:backend.LauncherTool):Promise<backend.LauncherTool>;

export function AddPromptTemplate(arg1:backend.PromptTemplate):Promise<backend.PromptTemplate>;

export function AddPromptToolLink(arg1:backend.PromptToolLink):Promise<backend.PromptToolLink>;

export function AddTagToImage(arg1:string,arg2:string):Promise<Array<string>>;

export function BatchAddTag(arg1:Array<string>,arg2:string):Promise<number>;

export function BatchDeleteTags(arg1:Array<string>):Promise<number>;

export function BatchDeleteTrash(arg1:Array<string>):Promise<number>;

export function BatchFavorites(arg1:Array<string>,arg2:string):Promise<number>;

export function BatchMove(arg1:Array<string>,arg2:string):Promise<number>;

export function BatchRemoveTag(arg1:Array<string>,arg2:string):Promise<number>;

export function BatchRestoreTrash(arg1:Array<string>):Promise<number>;

export function CleanEmptyFolders():Promise<number>;

export function CleanupFavoriteReferences():Promise<number>;

export function CleanupTags():Promise<number>;

export function ClearPreviewCache():Promise<backend.CacheClearResult>;

export function ClearUserProfileImage():Promise<backend.UserProfile>;

export function CopyText(arg1:string):Promise<void>;

export function CreateAutoRule(arg1:backend.AutoRule):Promise<backend.AutoRule>;

export function CreateFavoriteGroup(arg1:string):Promise<backend.FavoriteGroup>;

export function CreateTag(arg1:string,arg2:string,arg3:string):Promise<backend.Tag>;

export function DeleteAutoRule(arg1:string):Promise<void>;

export function DeleteCustomPromptEntry(arg1:string):Promise<void>;

export function DeleteCustomRoot(arg1:string):Promise<void>;

export function DeleteFavoriteGroup(arg1:string):Promise<void>;

export function DeleteImage(arg1:string):Promise<void>;

export function DeleteImageNote(arg1:string):Promise<void>;

export function DeleteLauncherTool(arg1:string):Promise<void>;

export function DeletePromptTemplate(arg1:string):Promise<void>;

export function DeletePromptToolLink(arg1:string):Promise<void>;

export function DeleteTag(arg1:string):Promise<void>;

export function EmptyTrash():Promise<number>;

export function ExportImages(arg1:Array<string>,arg2:string,arg3:boolean):Promise<number>;

export function ExtractIcon(arg1:string):Promise<string>;

export function GetAutoRules():Promise<backend.AutoRulesStore>;

export function GetCustomPromptEntries():Promise<Array<backend.PromptLibraryEntry>>;

export function GetCustomRoots():Promise<Array<backend.CustomRoot>>;

export function GetDirectoryBinding():Promise<backend.DirectoryBinding>;

export function GetDirectoryHealthSummary():Promise<backend.DirectoryHealthSummary>;

export function GetFavoriteGroups():Promise<Array<backend.FavoriteGroup>>;

export function GetFavorites():Promise<Array<string>>;

export function GetGalleryPerformanceSettings():Promise<backend.GalleryPerformanceSettings>;

export function GetImageGallerySummary():Promise<backend.ImageGallerySummary>;

export function GetImageMetadata(arg1:string):Promise<backend.ImageMetadata>;

export function GetImageNotes():Promise<backend.ImageNotesMap>;

export function GetImageTags():Promise<backend.ImageTagsMap>;

export function GetImages(arg1:string,arg2:string):Promise<Array<backend.ImageFile>>;

export function GetImagesIndex(arg1:string,arg2:string):Promise<Array<backend.ImageFile>>;

export function GetImagesPage(arg1:backend.GetImagesPageQuery):Promise<backend.GetImagesPageResult>;

export function GetLauncherTools():Promise<Array<backend.LauncherTool>>;

export function GetPromptAssistantState():Promise<backend.PromptAssistantState>;

export function GetPromptLibraryEntries():Promise<Array<backend.PromptLibraryEntry>>;

export function GetPromptTemplates():Promise<Array<backend.PromptTemplate>>;

export function GetPromptToolLinks():Promise<Array<backend.PromptToolLink>>;

export function GetRelativePath(arg1:string):Promise<string>;

export function GetShortcutActions():Promise<Array<backend.ShortcutAction>>;

export function GetShortcutSettings():Promise<backend.ShortcutSettings>;

export function GetStatistics(arg1:string):Promise<backend.Stats>;

export function GetSubFolders(arg1:string):Promise<Array<string>>;

export function GetTags():Promise<Array<backend.Tag>>;

export function GetTrashList():Promise<Array<backend.TrashItem>>;

export function GetTrashSettings():Promise<backend.Settings>;

export function GetUserProfile():Promise<backend.UserProfile>;

export function GetUtilityMenuSettings():Promise<backend.UtilityMenuState>;

export function GetWindowBehaviorSettings():Promise<backend.WindowBehaviorSettings>;

export function GetWorkbenchAggregate(arg1:backend.WorkbenchSummaryQuery):Promise<backend.WorkbenchAggregateResult>;

export function MoveCustomRoot(arg1:string,arg2:string):Promise<void>;

export function OpenCurrentOutputDirectory():Promise<void>;

export function OpenCurrentRootDirectory():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenImageLocation(arg1:string):Promise<void>;

export function OrganizeFiles(arg1:string):Promise<number>;

export function PinCustomRoot(arg1:string):Promise<void>;

export function RemoveFavorite(arg1:string):Promise<void>;

export function RemoveImageFromFavoriteGroup(arg1:string,arg2:string):Promise<void>;

export function RemoveTagFromImage(arg1:string,arg2:string):Promise<void>;

export function RestoreMainWindow():Promise<void>;

export function RestoreTrash(arg1:string):Promise<string>;

export function RunAutoRulesNow():Promise<backend.AutoRulesRunSummary>;

export function RunDirectoryHealthAction(arg1:string):Promise<backend.DirectoryHealthSummary>;

export function RunLauncherTool(arg1:string):Promise<void>;

export function SaveDirectoryBinding(arg1:string,arg2:string):Promise<backend.DirectoryBinding>;

export function SaveGalleryPerformanceSettings(arg1:backend.GalleryPerformanceSettings):Promise<backend.GalleryPerformanceSettings>;

export function SaveOutputDirectory(arg1:string):Promise<backend.DirectoryBinding>;

export function SavePromptAssistantState(arg1:backend.PromptAssistantState):Promise<backend.PromptAssistantState>;

export function SaveShortcutSettings(arg1:backend.ShortcutSettings):Promise<backend.ShortcutSettings>;

export function SaveTrashSettings(arg1:backend.Settings):Promise<void>;

export function SaveUserProfile(arg1:backend.UserProfile):Promise<backend.UserProfile>;

export function SaveUtilityMenuSettings(arg1:backend.UtilityMenuState):Promise<backend.UtilityMenuState>;

export function SelectFolder():Promise<string>;

export function SelectUserProfileImage():Promise<backend.UserProfile>;

export function ServeImage(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;

export function SetAutoRulesEnabled(arg1:boolean):Promise<backend.AutoRulesStore>;

export function SetImageFavoriteGroups(arg1:string,arg2:Array<string>):Promise<void>;

export function SetImageNote(arg1:string,arg2:string):Promise<void>;

export function ShowCompactWindow():Promise<void>;

export function ToggleAlwaysOnTop(arg1:boolean):Promise<backend.WindowBehaviorSettings>;

export function UpdateAutoRule(arg1:backend.AutoRule):Promise<backend.AutoRule>;

export function UpdateCustomRoot(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateCustomRootEnabled(arg1:string,arg2:boolean):Promise<void>;

export function UpdateFavoriteGroup(arg1:string,arg2:string):Promise<void>;

export function UpdateLauncherTool(arg1:string,arg2:backend.LauncherTool):Promise<void>;

export function UpdatePromptTemplate(arg1:string,arg2:backend.PromptTemplate):Promise<void>;

export function UpdatePromptToolLink(arg1:string,arg2:backend.PromptToolLink):Promise<void>;

export function UpdateTag(arg1:string,arg2:any,arg3:any,arg4:any):Promise<void>;

export function UploadImages(arg1:Array<string>,arg2:string):Promise<backend.UploadResult>;
