// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCustomPromptEntry(arg1:main.PromptLibraryEntry):Promise<main.PromptLibraryEntry>;

export function AddCustomRoot(arg1:string,arg2:string,arg3:string):Promise<main.CustomRoot>;

export function AddFavorite(arg1:string):Promise<void>;

export function AddImageToFavoriteGroup(arg1:string,arg2:string):Promise<void>;

export function AddLauncherTool(arg1:main.LauncherTool):Promise<main.LauncherTool>;

export function AddPromptTemplate(arg1:main.PromptTemplate):Promise<main.PromptTemplate>;

export function AddPromptToolLink(arg1:main.PromptToolLink):Promise<main.PromptToolLink>;

export function AddTagToImage(arg1:string,arg2:string):Promise<Array<string>>;

export function BatchAddTag(arg1:Array<string>,arg2:string):Promise<number>;

export function BatchDeleteTags(arg1:Array<string>):Promise<number>;

export function BatchDeleteTrash(arg1:Array<string>):Promise<number>;

export function BatchFavorites(arg1:Array<string>,arg2:string):Promise<number>;

export function BatchMove(arg1:Array<string>,arg2:string):Promise<number>;

export function BatchRemoveTag(arg1:Array<string>,arg2:string):Promise<number>;

export function BatchRestoreTrash(arg1:Array<string>):Promise<number>;

export function CleanEmptyFolders():Promise<number>;

export function CleanupTags():Promise<number>;

export function ClearPreviewCache():Promise<main.CacheClearResult>;

export function ClearUserProfileImage():Promise<main.UserProfile>;

export function CopyText(arg1:string):Promise<void>;

export function CreateAutoRule(arg1:main.AutoRule):Promise<main.AutoRule>;

export function CreateFavoriteGroup(arg1:string):Promise<main.FavoriteGroup>;

export function CreateTag(arg1:string,arg2:string,arg3:string):Promise<main.Tag>;

export function DeleteAutoRule(arg1:string):Promise<void>;

export function DeleteCustomPromptEntry(arg1:string):Promise<void>;

export function DeleteCustomRoot(arg1:string):Promise<void>;

export function DeleteFavoriteGroup(arg1:string):Promise<void>;

export function DeleteImage(arg1:string):Promise<void>;

export function DeleteImageNote(arg1:string):Promise<void>;

export function DeleteLauncherTool(arg1:string):Promise<void>;

export function DeletePromptTemplate(arg1:string):Promise<void>;

export function DeletePromptToolLink(arg1:string):Promise<void>;

export function DeleteTag(arg1:string):Promise<void>;

export function EmptyTrash():Promise<number>;

export function ExportImages(arg1:Array<string>,arg2:string,arg3:boolean):Promise<number>;

export function ExtractIcon(arg1:string):Promise<string>;

export function GetAutoRules():Promise<main.AutoRulesStore>;

export function GetCustomPromptEntries():Promise<Array<main.PromptLibraryEntry>>;

export function GetCustomRoots():Promise<Array<main.CustomRoot>>;

export function GetDirectoryBinding():Promise<main.DirectoryBinding>;

export function GetFavoriteGroups():Promise<Array<main.FavoriteGroup>>;

export function GetFavorites():Promise<Array<string>>;

export function GetImageMetadata(arg1:string):Promise<main.ImageMetadata>;

export function GetImageNotes():Promise<main.ImageNotesMap>;

export function GetImageTags():Promise<main.ImageTagsMap>;

export function GetImages(arg1:string,arg2:string):Promise<Array<main.ImageFile>>;

export function GetLauncherTools():Promise<Array<main.LauncherTool>>;

export function GetPromptAssistantState():Promise<main.PromptAssistantState>;

export function GetPromptLibraryEntries():Promise<Array<main.PromptLibraryEntry>>;

export function GetPromptTemplates():Promise<Array<main.PromptTemplate>>;

export function GetPromptToolLinks():Promise<Array<main.PromptToolLink>>;

export function GetRelativePath(arg1:string):Promise<string>;

export function GetShortcutActions():Promise<Array<main.ShortcutAction>>;

export function GetShortcutSettings():Promise<main.ShortcutSettings>;

export function GetStatistics(arg1:string):Promise<main.Stats>;

export function GetSubFolders(arg1:string):Promise<Array<string>>;

export function GetTags():Promise<Array<main.Tag>>;

export function GetTrashList():Promise<Array<main.TrashItem>>;

export function GetTrashSettings():Promise<main.Settings>;

export function GetUserProfile():Promise<main.UserProfile>;

export function GetUtilityMenuSettings():Promise<main.UtilityMenuState>;

export function MoveCustomRoot(arg1:string,arg2:string):Promise<void>;

export function OpenCurrentOutputDirectory():Promise<void>;

export function OpenCurrentRootDirectory():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenImageLocation(arg1:string):Promise<void>;

export function OrganizeFiles(arg1:string):Promise<number>;

export function RemoveFavorite(arg1:string):Promise<void>;

export function RemoveImageFromFavoriteGroup(arg1:string,arg2:string):Promise<void>;

export function RemoveTagFromImage(arg1:string,arg2:string):Promise<void>;

export function RestoreTrash(arg1:string):Promise<string>;

export function RunAutoRulesNow():Promise<main.AutoRulesRunSummary>;

export function RunLauncherTool(arg1:string):Promise<void>;

export function SaveDirectoryBinding(arg1:string,arg2:string):Promise<main.DirectoryBinding>;

export function SaveOutputDirectory(arg1:string):Promise<main.DirectoryBinding>;

export function SavePromptAssistantState(arg1:main.PromptAssistantState):Promise<main.PromptAssistantState>;

export function SaveShortcutSettings(arg1:main.ShortcutSettings):Promise<main.ShortcutSettings>;

export function SaveTrashSettings(arg1:main.Settings):Promise<void>;

export function SaveUserProfile(arg1:main.UserProfile):Promise<main.UserProfile>;

export function SaveUtilityMenuSettings(arg1:main.UtilityMenuState):Promise<main.UtilityMenuState>;

export function SelectFolder():Promise<string>;

export function SelectUserProfileImage():Promise<main.UserProfile>;

export function SetAutoRulesEnabled(arg1:boolean):Promise<main.AutoRulesStore>;

export function SetImageFavoriteGroups(arg1:string,arg2:Array<string>):Promise<void>;

export function SetImageNote(arg1:string,arg2:string):Promise<void>;

export function UpdateAutoRule(arg1:main.AutoRule):Promise<main.AutoRule>;

export function UpdateCustomRoot(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateCustomRootEnabled(arg1:string,arg2:boolean):Promise<void>;

export function UpdateFavoriteGroup(arg1:string,arg2:string):Promise<void>;

export function UpdateLauncherTool(arg1:string,arg2:main.LauncherTool):Promise<void>;

export function UpdatePromptTemplate(arg1:string,arg2:main.PromptTemplate):Promise<void>;

export function UpdatePromptToolLink(arg1:string,arg2:main.PromptToolLink):Promise<void>;

export function UpdateTag(arg1:string,arg2:any,arg3:any,arg4:any):Promise<void>;

export function UploadImages(arg1:Array<string>,arg2:string):Promise<main.UploadResult>;
