// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomRoot(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddCustomRoot'](arg1, arg2, arg3);
}

export function AddFavorite(arg1) {
  return window['go']['main']['App']['AddFavorite'](arg1);
}

export function AddImageToFavoriteGroup(arg1, arg2) {
  return window['go']['main']['App']['AddImageToFavoriteGroup'](arg1, arg2);
}

export function AddLauncherTool(arg1) {
  return window['go']['main']['App']['AddLauncherTool'](arg1);
}

export function AddPromptTemplate(arg1) {
  return window['go']['main']['App']['AddPromptTemplate'](arg1);
}

export function AddPromptToolLink(arg1) {
  return window['go']['main']['App']['AddPromptToolLink'](arg1);
}

export function AddTagToImage(arg1, arg2) {
  return window['go']['main']['App']['AddTagToImage'](arg1, arg2);
}

export function BatchAddTag(arg1, arg2) {
  return window['go']['main']['App']['BatchAddTag'](arg1, arg2);
}

export function BatchDeleteTags(arg1) {
  return window['go']['main']['App']['BatchDeleteTags'](arg1);
}

export function BatchDeleteTrash(arg1) {
  return window['go']['main']['App']['BatchDeleteTrash'](arg1);
}

export function BatchFavorites(arg1, arg2) {
  return window['go']['main']['App']['BatchFavorites'](arg1, arg2);
}

export function BatchMove(arg1, arg2) {
  return window['go']['main']['App']['BatchMove'](arg1, arg2);
}

export function BatchRemoveTag(arg1, arg2) {
  return window['go']['main']['App']['BatchRemoveTag'](arg1, arg2);
}

export function BatchRestoreTrash(arg1) {
  return window['go']['main']['App']['BatchRestoreTrash'](arg1);
}

export function CleanEmptyFolders() {
  return window['go']['main']['App']['CleanEmptyFolders']();
}

export function CleanupTags() {
  return window['go']['main']['App']['CleanupTags']();
}

export function ClearPreviewCache() {
  return window['go']['main']['App']['ClearPreviewCache']();
}

export function ClearUserProfileImage() {
  return window['go']['main']['App']['ClearUserProfileImage']();
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function CreateAutoRule(arg1) {
  return window['go']['main']['App']['CreateAutoRule'](arg1);
}

export function CreateFavoriteGroup(arg1) {
  return window['go']['main']['App']['CreateFavoriteGroup'](arg1);
}

export function CreateTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2, arg3);
}

export function DeleteAutoRule(arg1) {
  return window['go']['main']['App']['DeleteAutoRule'](arg1);
}

export function DeleteCustomRoot(arg1) {
  return window['go']['main']['App']['DeleteCustomRoot'](arg1);
}

export function DeleteFavoriteGroup(arg1) {
  return window['go']['main']['App']['DeleteFavoriteGroup'](arg1);
}

export function DeleteImage(arg1) {
  return window['go']['main']['App']['DeleteImage'](arg1);
}

export function DeleteImageNote(arg1) {
  return window['go']['main']['App']['DeleteImageNote'](arg1);
}

export function DeleteLauncherTool(arg1) {
  return window['go']['main']['App']['DeleteLauncherTool'](arg1);
}

export function DeletePromptTemplate(arg1) {
  return window['go']['main']['App']['DeletePromptTemplate'](arg1);
}

export function DeletePromptToolLink(arg1) {
  return window['go']['main']['App']['DeletePromptToolLink'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function EmptyTrash() {
  return window['go']['main']['App']['EmptyTrash']();
}

export function ExportImages(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportImages'](arg1, arg2, arg3);
}

export function ExtractIcon(arg1) {
  return window['go']['main']['App']['ExtractIcon'](arg1);
}

export function GetAutoRules() {
  return window['go']['main']['App']['GetAutoRules']();
}

export function GetCustomRoots() {
  return window['go']['main']['App']['GetCustomRoots']();
}

export function GetDirectoryBinding() {
  return window['go']['main']['App']['GetDirectoryBinding']();
}

export function GetFavoriteGroups() {
  return window['go']['main']['App']['GetFavoriteGroups']();
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetImageMetadata(arg1) {
  return window['go']['main']['App']['GetImageMetadata'](arg1);
}

export function GetImageNotes() {
  return window['go']['main']['App']['GetImageNotes']();
}

export function GetImageTags() {
  return window['go']['main']['App']['GetImageTags']();
}

export function GetImages(arg1, arg2) {
  return window['go']['main']['App']['GetImages'](arg1, arg2);
}

export function GetLauncherTools() {
  return window['go']['main']['App']['GetLauncherTools']();
}

export function GetPromptTemplates() {
  return window['go']['main']['App']['GetPromptTemplates']();
}

export function GetPromptToolLinks() {
  return window['go']['main']['App']['GetPromptToolLinks']();
}

export function GetRelativePath(arg1) {
  return window['go']['main']['App']['GetRelativePath'](arg1);
}

export function GetShortcutActions() {
  return window['go']['main']['App']['GetShortcutActions']();
}

export function GetShortcutSettings() {
  return window['go']['main']['App']['GetShortcutSettings']();
}

export function GetStatistics(arg1) {
  return window['go']['main']['App']['GetStatistics'](arg1);
}

export function GetSubFolders(arg1) {
  return window['go']['main']['App']['GetSubFolders'](arg1);
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function GetTrashList() {
  return window['go']['main']['App']['GetTrashList']();
}

export function GetTrashSettings() {
  return window['go']['main']['App']['GetTrashSettings']();
}

export function GetUserProfile() {
  return window['go']['main']['App']['GetUserProfile']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenImageLocation(arg1) {
  return window['go']['main']['App']['OpenImageLocation'](arg1);
}

export function OrganizeFiles(arg1) {
  return window['go']['main']['App']['OrganizeFiles'](arg1);
}

export function RemoveFavorite(arg1) {
  return window['go']['main']['App']['RemoveFavorite'](arg1);
}

export function RemoveImageFromFavoriteGroup(arg1, arg2) {
  return window['go']['main']['App']['RemoveImageFromFavoriteGroup'](arg1, arg2);
}

export function RemoveTagFromImage(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagFromImage'](arg1, arg2);
}

export function RestoreTrash(arg1) {
  return window['go']['main']['App']['RestoreTrash'](arg1);
}

export function RunAutoRulesNow() {
  return window['go']['main']['App']['RunAutoRulesNow']();
}

export function RunLauncherTool(arg1) {
  return window['go']['main']['App']['RunLauncherTool'](arg1);
}

export function SaveDirectoryBinding(arg1, arg2) {
  return window['go']['main']['App']['SaveDirectoryBinding'](arg1, arg2);
}

export function SaveShortcutSettings(arg1) {
  return window['go']['main']['App']['SaveShortcutSettings'](arg1);
}

export function SaveTrashSettings(arg1) {
  return window['go']['main']['App']['SaveTrashSettings'](arg1);
}

export function SaveUserProfile(arg1) {
  return window['go']['main']['App']['SaveUserProfile'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectUserProfileImage() {
  return window['go']['main']['App']['SelectUserProfileImage']();
}

export function SetAutoRulesEnabled(arg1) {
  return window['go']['main']['App']['SetAutoRulesEnabled'](arg1);
}

export function SetImageFavoriteGroups(arg1, arg2) {
  return window['go']['main']['App']['SetImageFavoriteGroups'](arg1, arg2);
}

export function SetImageNote(arg1, arg2) {
  return window['go']['main']['App']['SetImageNote'](arg1, arg2);
}

export function UpdateAutoRule(arg1) {
  return window['go']['main']['App']['UpdateAutoRule'](arg1);
}

export function UpdateCustomRoot(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCustomRoot'](arg1, arg2, arg3);
}

export function UpdateFavoriteGroup(arg1, arg2) {
  return window['go']['main']['App']['UpdateFavoriteGroup'](arg1, arg2);
}

export function UpdateLauncherTool(arg1, arg2) {
  return window['go']['main']['App']['UpdateLauncherTool'](arg1, arg2);
}

export function UpdatePromptTemplate(arg1, arg2) {
  return window['go']['main']['App']['UpdatePromptTemplate'](arg1, arg2);
}

export function UpdatePromptToolLink(arg1, arg2) {
  return window['go']['main']['App']['UpdatePromptToolLink'](arg1, arg2);
}

export function UpdateTag(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTag'](arg1, arg2, arg3, arg4);
}

export function UploadImages(arg1, arg2) {
  return window['go']['main']['App']['UploadImages'](arg1, arg2);
}
